from typing import Dict, Any, List

class Explainer:
    def __init__(self):
        # In a real implementation, you would load the SHAP explainer
        # and Grad-CAM utilities here.
        pass

    def generate_explanation(self, cnn_result: Dict[str, Any], xgb_result: Dict[str, Any], static_features: Dict[str, Any], dynamic_features: Dict[str, Any]) -> Dict[str, Any]:
        """
        Generate mock SHAP and top feature explanations for the UI.
        """
        top_features = []
        
        # 1. Analyze XGBoost features (Simulating SHAP feature importance)
        if xgb_result.get("is_malware"):
            if static_features.get("entropy", 0) > 7.0:
                top_features.append({
                    "feature": "High File Entropy (Packed/Encrypted)",
                    "importance": 0.85
                })
            
            suspicious_strings = static_features.get("suspicious_strings", [])
            if suspicious_strings:
                top_features.append({
                    "feature": f"Suspicious Strings Detected ({len(suspicious_strings)})",
                    "importance": 0.78
                })
                
            api_calls = dynamic_features.get("api_calls", [])
            if "VirtualAllocEx" in api_calls or "WriteProcessMemory" in api_calls:
                 top_features.append({
                    "feature": "Suspicious Process Injection APIs",
                    "importance": 0.92
                })
        
        # 2. Mock Grad-CAM path
        gradcam_path = None
        if cnn_result.get("family") not in ["Benign", None]:
            gradcam_path = "/uploads/mock_gradcam.png" # Should be generated by a real Grad-CAM function
            
        return {
            "top_features": top_features,
            "gradcam": gradcam_path,
            "shap": [{"name": f["feature"], "value": f["importance"]} for f in top_features]
        }
